services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}    # Base de données Airflow
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf  # Monte le fichier my.cnf
    networks:
      - airflow_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    networks:
      - airflow_network

  jupyter:
    build: ./jupyter
    image: jupyter
    container_name: jupyter
    volumes:
      - ./notebooks:/home/jovyan/work # Montage des notebooks Jupyter
    ports:
      - "8887:8888" # Exposition du port Jupyter
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      SUPERSTORE_MYSQL_DATABASE: ${SUPERSTORE_MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  
      JUPYTER_ENABLE_LAB: "yes"
    command: start-notebook.sh --NotebookApp.token=''
    depends_on:
      - mysql
    networks:
      - airflow_network

  airflow:
    build: ./airflow
    image: airflow
    container_name: airflow
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql://${MYSQL_ROOT}:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  
      SUPERSTORE_MYSQL_DATABASE: ${SUPERSTORE_MYSQL_DATABASE}
      DATA_FILE_PATH: ${DATA_FILE_PATH}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - .${DATA_FILE_PATH}:${DATA_FILE_PATH}
    ports:
      - "8080:8080"
    depends_on: 
      - mysql
    command: >
      bash -c " 
        airflow db init || airflow db upgrade;
        airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com;
        airflow scheduler & airflow webserver
      "
    networks:
      - airflow_network

volumes:
  mysql_data: # Définition du volume pour le stockage persistant des données MySQL

networks:
  airflow_network:
