FROM jupyter/datascience-notebook:latest

# Installer des packages supplémentaires si nécessaire
RUN pip install mysql-connector-python pandas SQLAlchemy PyMySQL

# Exposer le port 8888 pour Jupyter
EXPOSE 8888
